import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import { NavigationMenu, NavigationMenuLink } from '@/components/ui/navigation-menu';
import QueryProvider from '@/components/provider/QueryProvider';

const pretendard = localFont({
  src: '../public/fonts/pretendard/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Juniverse Dev: Admin',
  description: 'Generated by create next app',
};

const ROUTES = [
  {
    path: '/',
    label: 'HOME',
  },
  {
    path: '/career',
    label: 'CAREER',
  },
  {
    path: '/tech',
    label: 'TECH',
  },
  {
    path: '/project',
    label: 'PROJECT',
  },
  {
    path: '/blog',
    label: 'BLOG',
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.className} m-12`}>
        <NavigationMenu className={'text-lg font-bold'}>
          {ROUTES.map((item) => (
            <NavigationMenuLink key={item.label} className={'px-5 text-lg'} href={item.path}>
              {item.label}
            </NavigationMenuLink>
          ))}
        </NavigationMenu>
        <QueryProvider>
          <main>{children}</main>
        </QueryProvider>
      </body>
    </html>
  );
}
